// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSta5QLfVf_FTauYvYndnXg9UObnVJYs',
    appId: '1:623326298726:web:16e35ac6eb85396d35a3a7',
    messagingSenderId: '623326298726',
    projectId: 'credit-risk-checker-v1',
    authDomain: 'credit-risk-checker-v1.firebaseapp.com',
    storageBucket: 'credit-risk-checker-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYqgCz7IfOUtslzJi6Mv82-y-3xaD2YY',
    appId: '1:623326298726:android:0300e09581d8cf1235a3a7',
    messagingSenderId: '623326298726',
    projectId: 'credit-risk-checker-v1',
    storageBucket: 'credit-risk-checker-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszrynrH3vQGVen9mpJ7OnfSjSnqMCVPc',
    appId: '1:623326298726:ios:41c5b13f8360aee735a3a7',
    messagingSenderId: '623326298726',
    projectId: 'credit-risk-checker-v1',
    storageBucket: 'credit-risk-checker-v1.firebasestorage.app',
    iosBundleId: 'com.example.creditRiskV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCszrynrH3vQGVen9mpJ7OnfSjSnqMCVPc',
    appId: '1:623326298726:ios:41c5b13f8360aee735a3a7',
    messagingSenderId: '623326298726',
    projectId: 'credit-risk-checker-v1',
    storageBucket: 'credit-risk-checker-v1.firebasestorage.app',
    iosBundleId: 'com.example.creditRiskV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSta5QLfVf_FTauYvYndnXg9UObnVJYs',
    appId: '1:623326298726:web:20045baf29ef380535a3a7',
    messagingSenderId: '623326298726',
    projectId: 'credit-risk-checker-v1',
    authDomain: 'credit-risk-checker-v1.firebaseapp.com',
    storageBucket: 'credit-risk-checker-v1.firebasestorage.app',
  );
}
